title: Qompoter
description: Dependency manager for Qt / C++
google_analytics:
show_downloads: true
theme: jekyll-theme-architect
release:
  version: 0.4.1
  url: https://github.com/Fylhan/qompoter/releases/download/v0.4.1/qompoter.sh
nightly:
  url: https://github.com/Fylhan/qompoter/blob/master/qompoter.sh

gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
